### ISSUE TITLE
CUDA errors in posteriors calculation

### ISSUE THREAD

**Issue by stachu86** [ebattenberg/ggmm#5]
I'm trying tu run gmm.fit() but I get err_code = -3 in posterior calculation, but last cuda error is: no error. I use CUDA 6.5, but had same problem with CUDA 5.5, my OS is Debian
```
Traceback (most recent call last):
invalid argument
File "/home/user/Pobrane/pycasp-master/tests/gmm_test.py", line 22, in <module>
    gmm.fit(X, thresh, n_iter, init_params=init_params, n_init=10)
  File "/home/user/libs/ggmm/gpu.py", line 596, in fit
    X_gpu, temp_gpu_mem)
  File "/home/user/libs/ggmm/gpu.py", line 437, in score_samples
    vmax_Nx1 = posteriors_NxK.max(axis=1, target=None)
  File "/home/user/libs/cudamat/cudamat.py", line 718, in max
    check_error(_cudamat.max_by_axis(self.p_mat, target.p_mat, ct.c_int(axis))) #TODO
  File "/home/user/libs/cudamat/cudamat.py", line 157, in check_error
    raise CUDAMatException("CUDA error: " + get_last_cuda_error())
cudamat.cudamat.CUDAMatException: CUDA error: no error
```
Any help will be appreciated.

**Comment by stachu86** [comment]
I solved this problem by specifying `nvcc` parameters `-arch` and `-code` (with values suitable to my GPU) in cudamat Makefile.

**Comment by ebattenberg** [comment]
Thanks for following up on this.  

I'm glad you were able to fix this problem.  The lack of info in the error message  ("CUDA error: no error") seems to be due to error reporting problems in CUDAMat.  These may have been addressed in the current CUDAMat main repo.  I'm not sure if my fork of CUDAMat is required anymore as the features I've added have been merged into the main line.  

Would you be willing to test ggmm with the latest version of CUDAMat (https://github.com/cudamat/cudamat)?

**Comment by ebattenberg** [comment]
Moved the CUDAMat mainline integration to #6

**Comment by stachu86** [comment]
I tested ggmm with latest cudamat and it worked - my code with ggmm worked and all ggmm tests passed. No need for my modification in compiler options. Thanks for update on that matter.
